### ISSUE TITLE
Laser project

### ISSUE THREAD

**Issue by colindoughty** [JWSmythe/MarlinLaser#2]
Hello,
 
I have almost finished my laser machine, (see attached jpg.) I have it running but not the laser head just yet. I will be using an air pump and wondering if you have added the control for this yet.
 
In VScode I see some errors with the gcode. see attachment. 
Is this important or just a warning?
With regard to the drivers, I am using the Creality 4.2.2 board that has the HR4988 drivers which marlin doesn't support but A4988 works fine.
 I would be grateful if you would reply.

![20240909_173805](https://github.com/user-attachments/assets/041a3bb6-36a0-4f13-a4fd-712ffcdf4296)
![Screenshot 2024-09-09 172249](https://github.com/user-attachments/assets/1799e7fd-2af9-4a56-ad4c-d60f40b90d40)

**Comment by JWSmythe** [comment]
I've never seen that before.  It looks like the Marlin source may be corrupted.  Download the full source again from marlinfw.org, and extract it to a new directory.   You can test compile it with the default Conf*.h files, just to see that it doesn't throw those warnings.  If it still does, you might want to ask for help in one of the Marlin groups, or the official Github.

And yes, the 4.2.2 board should work just as well for you.  You'll just get a little noise from the steppers.

**Comment by colindoughty** [comment]
Thank you for your reply.
I have it working (sort off).   When I laser fire at 80% for 2 seconds, it marks (burns) the wood. When I fire at 255% there is no noticeable difference. It's as though the PWM is not controlling correctly.

When I run a gcode file from Lightburn it won't fire on the PWM laser even though I have the gcode included in the devise settings--------- 
; In Marlin, inline mode is enabled with 'M3 I' and disabled with 'M5 I'.
 M3 I  
I have looked at the gcode and M3-M5 are included through out the file. see sample below.

I have spent a lot of time trying to figure this out but so far its got me beat. Any ideas??

![image](https://github.com/user-attachments/assets/001f55bc-6b1c-4ff6-a406-a6091417868e)

**Comment by JWSmythe** [comment]
I don't have any good answers for you, but I can offer some questions.  

If you use the test fire on the LCD, and set it for high and low powers (like 10% and 90%), do they look like it's changing the PWM?  Like, does the 10% show dim.  If it doesn't, you might need to change the laser to another PWM pin.   I picked that pin because it had the cleanest PWM, but any GPIO pin should work.  If you have an oscilloscope, this would be a good time to hook it up so you can see what's actually being sent down the wire.  

It also looks like you have a couple typos.  The G0/G1 lines with F6000 need a space.  That wouldn't break the laser though.

Try going more extreme with your M03 lines.  Like M03 S25 (10% power) and M03 S230 (90% power).  Also, double check that the PWM pin is really going to the PWM pin on the laser.

**Comment by colindoughty** [comment]
I have gone back to using BLTouch IN PWM pin.  The center pin. 
Should I see some voltage there when I test fire re the LCD? because there is no voltage at all, just zero volts. but when its not firing I see -8 volts?? ...........the laser doesn't fire at all of course.  
With the test fire OFF I read on my digital multi meter -8 volts (minus 8 volts) and with the test fire ON I read 0 volts (zero volts).    I'm using a digital multi meter and can't read the PWM correctly but doesn't it show the PWM is working? and the laser module maybe at fault??

This board is normally run at 24 volts and I have it supplied at 12 volts. maybe that's the problem, I  wouldn't have thought so.
I haven't bothered running any files as I need to successfully get a test fire first.

**Comment by colindoughty** [comment]
I have just ordered a GRBL32  board.

**Comment by colindoughty** [comment]
The new board is going great.
